### ISSUE TITLE
Lower testing of RTM in CESM3

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/RTM#42]
Should RTM continue to be distributed as a part of CESM3? 
If so why?

**Comment by jedwards4b** [comment]
I propose that we remove the following RTM based tests from ctsm:

testlist_clm.xml:  <test name="ERP_D_P36x2_Ld5" grid="f10_f10_mg37" compset="I2000Clm50BgcCropRtm" testmods="clm/irrig_spunup">
testlist_clm.xml:      <option name="comment"  >Include an irrigation test with RTM to test irrigation-river feedbacks with that component</option>
testlist_clm.xml:  <test name="ERS_D_Ld5" grid="f10_f10_mg37" compset="I2000Clm50BgcCropRtm" testmods="rtm/rtmOnFloodOnEffvelOn">
testlist_clm.xml:      <option name="comment"  >Do a test with RTM and flooding on as that also impacts CLM code</option>
testlist_clm.xml:  <test name="ERP_P36x2_D" grid="f10_f10_mg37" compset="I2000Clm50SpRtmFl" testmods="clm/default">
testlist_clm.xml:  <test name="SSP_D_Ld10" grid="f10_f10_mg37" compset="I1850Clm51Bgc" testmods="clm/rtmColdSSP">
testlist_clm.xml:  <test name="SSP_D_Ld4" grid="f10_f10_mg37" compset="I1850Clm50BgcCrop" testmods="clm/ciso_rtmColdSSP">
testlist_clm.xml:  <test name="SSP_Ld10" grid="f10_f10_mg37" compset="I1850Clm50Bgc" testmods="clm/rtmColdSSP">
testlist_clm.xml:  <test name="SSP_Ld4" grid="f09_g17" compset="I1850Clm50BgcCrop" testmods="clm/ciso_rtmColdSSP">

**Comment by ekluzek** [comment]
Unfortunately the answer is yes, until we can move over to mizuRoute (where upon we can remove both MOSART and RTM and just support one river model). The reason we need RTM is for Paleo work, primarily because we don't have the ability to make river network input datasets for MOSART. So we need to keep RTM around for Paleo efforts, and MOSART for the standard model.

**Comment by ekluzek** [comment]
However, I think you are right we could reduce the testing of RTM. Maybe keeping one test just for aux_clm, and only do a few tests when RTM tags are made.

**Comment by ekluzek** [comment]
Will got confirmation from the Paleo group that we do indeed need RTM for CESM3.

> Hi Will,
> 
> Thank you so much for the email!
> 
> Yes, we still need RTM for a couple of reasons. First, we expect to use it for future paleoclimate simulations with altered land-sea distribution, such as the Last Glacial Maximum, Pliocene, and Eocene. For such paleoclimates, we don't have detailed geological information to properly set up MOSART or mizuRoute. Unless future versions of mizuRoute have simplified configuration for paleo we will have to use RTM. Please note that RTM was used in CESM2 LGM, Pliocene and Eocene simulations, which contributed to PMIP4, PlioMIP, and DeepMIP.
> Second, iCESM1 is the supported CESM configuration with the water isotope capability, per CESM support policy. Having RTM supported in CESMe would help with future development of isotopes.
> 
> Happy holidays!
> Jiang

I've added issues to mizuRoute about supporting mizuRoute for Paleo work in CESM4.

https://github.com/ESCOMP/mizuRoute/issues/447

On the RTM issue in iCESM1, since the RTM there is a separate model from the RTM used in CESM, I see no need to include it for CESM4 if mizuRoute works sufficiently well for Paleo users.

**Comment by jedwards4b** [comment]
Thank you for confirming.
